<section id="games">
   <h2>Games</h2>
   <ul class="gamesList">
   <? foreach($this->games as $game) { ?>
      <li>
        <span class="gameTitle"><? echo($game->title) ?></span>
        <span class="gameVotes">Votes: <? echo($game->votes) ?></span>
        <span class="gameOwned"><? echo($game->status) ?></span>
        <span class="gameTime"><? echo($game->votetime) ?></span>
      </li>
   <? } ?>
   </ul>
</section>
