<!doctype html>
<html>
   <head>
      <? echo $this->headTitle() ?>
      <? echo $this->headLink() ?>
      <? echo $this->headStyle() ?>
      <? echo $this->headScript() ?>
   </head>
   <body>
      <heading>
         <h1>Xbox Games Voting</h1>
      </header>
      <? echo $this->layout()->content ?>
      <footer>
      <p>Copyrighted &copy;2012 Dwight Spencer. All Rights Reserved.</p>
      </footer>
   </body>
</html>
